spring.application.name=trustchain


spring.datasource.url=jdbc:postgresql://ep-polished-bonus-aslcnwou-pooler.c-4.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_GC93xUnXBhPE

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.flyway.enabled=false



